### ISSUE TITLE
Bandwidth throttle over wifi

### ISSUE THREAD

**Issue by 0xrushi** [ovedanner/bandwidth-throttler#1]
will this script to control bandwidth of others in my wifi network ? if yes what will be the syntax ?

also please  atleast put your email/telegram id in about section

**Comment by ovedanner** [comment]
Hi @rushic24,
All the bandwidth throttling is done on the client itself. The bash script throttles ingress and egress traffic, optionally based on IP. The python scripts are just there to have a centralized way of increasing/decreasing bandwidth throttling from one central point (the server). Don't forget that you need to put `shape_traffic.sh` in `/usr/bin/shape_traffic` on the clients for `shape_traffic_client.py` to work properly.

**Comment by 0xrushi** [comment]
oh 😅i just found what i wanted , ita on my github under name bandwidth
control

**Comment by ovedanner** [comment]
nice, good luck!
